### ISSUE TITLE
Using react-native-webrtc

### ISSUE THREAD

**Issue by taimoorInvoZone** [jellyfish-dev/react-native-membrane-webrtc#113]
We are using react-native-webrtc in our app and we tried to use this package along with it however on build there were duplicate classes issues of these two packages conflicting with each other, react-native-webrtc and @jellyfish/react-native-membrane-webrtc, is there any way i can use both packages?

**Comment by skyman503** [comment]
You don't need to use `react-native-webrtc` since `@jellyfish/react-native-membrane-webrtc` contains all of the webrtc logic, so if you wish to use jellyfish this library should be enough.

**Comment by taimoorInvoZone** [comment]
But i was already using react-native-webrtc packages, logic in my app, i need to further use membrane logic too, so what would i need to change to keep both logics.

**Comment by graszka22** [comment]
Hi @taimoorInvoZone!
- If you're just using membrane rtc engine without Jellyfish on your backend and not jellyfish you can still use `react-native-membrane-webrtc` and there is nothing you have to change
- if you're using jellyfish media server on your backend you'll have to migrate to [react-native-client-sdk](https://github.com/jellyfish-dev/react-native-client-sdk). It is based on `react-native-membrane-webrtc` and it will have very similar api (most of the hooks are in fact re-exported from `react-native-membrane-webrtc`) so probably you'll have to change only your connect function and some imports. Be warned though that `react-native-client-sdk` is still WIP, not released yet and we can still change the api. After it's done we're planning to write a guide for using the mobile clients. 
Hope this answers your question!

**Comment by taimoorInvoZone** [comment]
It seems, there has been a misunderstanding. I have two modules in my app, one is an audio call feature i have developed some time ago using another server that was based on react-native-webrtc, it is working. Now, i wanted to use your example app with the main application, and i was able to achieve that after removing the react-native-webrtc package and audio call. Now I want to use both but when I build using both packages it shows duplicate classes error, however there shouldn't be any link between these 2 packages.

**Comment by graszka22** [comment]
Ah you mean this library: https://github.com/react-native-webrtc/react-native-webrtc
Well it's possible we have similar dependencies since we're doing similar thing.
If I were you I'd decide to use just one library for webrtc if possible. It will be better for performance and maintenance of your app in the long term. Our sdk supports also audio only calls (I know one of the users uses it for just audio calls).

**Comment by taimoorInvoZone** [comment]
Thanks for the clarification. I guess, I have to use only one package in my app.
