### ISSUE TITLE
switching output audio source 

### ISSUE THREAD

**Issue by chanphiromsok** [jellyfish-dev/react-native-membrane-webrtc#144]
I used to work with livekit it has output audio like earpiece or speaker or connect with bluetooth device  does this option available in react-native-memebrane-werbrtc ?

**Comment by incubo4u** [comment]
switching between audio devices is possible using [selectOutputAudioDevice](https://github.com/jellyfish-dev/react-native-membrane-webrtc/blob/8818825ba2f3f178f8745351851959e8c41ffe7c/src/index.tsx#L604C9-L604C32) on Android and [showAudioRoutePicker](https://github.com/jellyfish-dev/react-native-membrane-webrtc/blob/8818825ba2f3f178f8745351851959e8c41ffe7c/src/index.tsx#L636C9-L636C29) on iOS

**Comment by incubo4u** [comment]
switching between audio devices is possible using [selectOutputAudioDevice](https://github.com/jellyfish-dev/react-native-membrane-webrtc/blob/8818825ba2f3f178f8745351851959e8c41ffe7c/src/index.tsx#L604C9-L604C32) on Android and [showAudioRoutePicker](https://github.com/jellyfish-dev/react-native-membrane-webrtc/blob/8818825ba2f3f178f8745351851959e8c41ffe7c/src/index.tsx#L636C9-L636C29) on iOS
