### ISSUE TITLE
Background on iOS

### ISSUE THREAD

**Issue by ciaoamigoschat** [jellyfish-dev/react-native-membrane-webrtc#148]
I'm trying out different libraries/servers to evaluate which ones to use in our projects. We've noticed that when the application is in the background on iOS and the user isn't listening to/transmitting video, the application disconnects from the server. Any solutions or suggestions for this?"

**Comment by Tonyhaenn** [comment]
I haven't observed the same behavior. Did you add the following to your info.plist?
```
 <key>UIBackgroundModes</key>
  <array>
    <string>audio</string>
  </array>
```
https://jellyfish-dev.github.io/react-native-membrane-webrtc/index.html

I'm using the expo plugin and it was automatically added for me.

**Comment by incubo4u** [comment]
Hi @ciaoamigoschat  👋
Could you please provide the info.plist file or any reproducible example? This behavior isn't normal, so having more details could help figure out a solution.
