### ISSUE TITLE
expo sdk 50 prebuild is not working

### ISSUE THREAD

**Issue by chanphiromsok** [jellyfish-dev/react-native-membrane-webrtc#159]
can not find module @expo/config-plugins

<img width="1331" alt="image" src="https://github.com/jellyfish-dev/react-native-membrane-webrtc/assets/65760336/bee9fbec-256e-450e-907b-1293766e43ab">

**Comment by chanphiromsok** [comment]
it was resolved by using the exact expo version defined in `@jellyfish-dev/react-native-membrane-webrtc` it is work now 
- ERROR when I use expo50.7
- WORK I upgrade to expo50.0.7

**Comment by karkakol** [comment]
Hello,
Thank you for your contribution.
Could you provide a minimum example to reproduce this issue, for example in a GitHub repository? It would be the easiest way for us to see where the potential issue could be and, if necessary, to fix it as soon as possible.

**Comment by chanphiromsok** [comment]
[clothify.zip](https://github.com/jellyfish-dev/react-native-membrane-webrtc/files/14415977/clothify.zip)


dont for get to run `chmod +x scripts/env.sh` give it permission to bash scripts then run `yarn prebuild:dev --no-install --clean && yarn android:dev` you will see error

**Comment by karkakol** [comment]
in provided example you don't use directly this repo ```jellyfish-dev/react-native-membrane-webrtc ```but  ```jellyfish-dev/react-native-client-sdk```, today i released version 0.1.6 which uses expo 50 and react native 0.73 it should work.

**Comment by chanphiromsok** [comment]
but server I don't use jellyfish I use membrane_etc and membrane_rtc_engine

**Comment by chanphiromsok** [comment]
ahhh sorry you are right I used to installed @jellyfish-dev/react-native-client-sdk that autocompletion and blind me did not pay attention to it
